### ISSUE TITLE
v2.0.0 Progress: Server-Side Integration

### ISSUE THREAD

**Issue by mega12345mega** [mega12345mega/NBT-Editor#83]
When the mod is loaded on the server, it should allow players with level 2 OP or above to do:

- [x] Item Editing
  - [x] Inventory in survival
  - [x] Containers in world
  - [x] Enderchest
- [x] Block Editing
  - [x] NBT
  - [x] Container
  - [x] Block states
  - [x] Name
  - [x] Lecturn book
  - [x] Signs
  - [x] Unbind skulls
- [x] Entity Editing
  - [x] NBT
  - [x] Container
  - [x] Name
  - [x] Attributes
- [x] Importing & Exporting
  - [x] Block -> /setblock, /get block, file
  - [x] Entity -> /summon, /get entity, file
  - [x] Block -> Block Item
  - [x] Entity -> Spawn Egg

**Comment by mega12345mega** [comment]
I've now added this in v2.0.0!
